/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.11 (r5902M) - 10 Mar 2016 10:58


  Differentiation of smallfunc in reverse (adjoint) mode:
   gradient     of useful results: *result arg0 arg1
   with respect to varying inputs: *result arg0 arg1
   RW status of diff variables: *result:in-zero arg0:incr arg1:incr
   Plus diff mem management of: result:in
*/
void smallfunc_b(double arg0, double *arg0b, double arg1, double *arg1b, 
        double arg2, double arg3, double arg4, double *result, double *resultb
) {
    double tmp0 = arg0*sin(arg0)/cos(arg1);
    double tmp0b;
    double tmp1 = arg1*sin(arg1)/cos(arg0);
    double tmp1b;
    double tmp2 = sin(tmp0)*tmp1 + sin(tmp1)*tmp0;
    double tmp2b;
    double tmp3;
    double tmp3b;
    double temp3;
    double temp2;
    double temp1;
    double temp0;
    double tempb0;
    double tempb;
    double temp;
    double temp4;
    temp = sin(arg0);
    tmp3b = *resultb;
    temp4 = cos(tmp2);
    temp3 = sin(tmp0);
    tmp2b = (sin(tmp2)*sin(tmp2)/(temp4*temp4)+cos(tmp2)/temp4)*tmp3b;
    tmp0b = (sin(tmp1)+tmp1*cos(tmp0))*tmp2b + (-(cos(tmp0)*cos(tmp0)/(temp3*
        temp3))-sin(tmp0)/temp3)*tmp3b;
    tmp1b = (tmp0*cos(tmp1)+sin(tmp0))*tmp2b;
    temp2 = cos(arg0);
    tempb = tmp1b/temp2;
    temp1 = sin(arg1);
    temp0 = cos(arg1);
    tempb0 = tmp0b/temp0;
    *arg1b = *arg1b + arg0*temp*sin(arg1)*tempb0/temp0 + (arg1*cos(arg1)+temp1
        )*tempb;
    *arg0b = *arg0b + (arg0*cos(arg0)+temp)*tempb0 + arg1*temp1*sin(arg0)*
        tempb/temp2;
    *resultb = 0.0;
}
